export const featuredProjects = [
  {
    number: '01',
    type: 'B2B / LEAD GENERATION',
    title: 'The Shubham Engineering',
    description: 'Architected a B2B industrial website optimized for lead inquiry flows.',
    platforms: ['B2B website', 'Lead generation'],
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=900&q=75',
    alt: 'Illustrative industrial engineering photograph; not a screenshot of the project website',
  },
  {
    number: '02',
    type: 'E-COMMERCE / MOBILE-FIRST',
    title: 'Shalimar Hosiery',
    description: 'Built an interactive e-commerce catalogue with a mobile-first UI experience.',
    platforms: ['E-commerce', 'Responsive UI'],
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=900&q=75',
    alt: 'Illustrative clothing photograph; not a screenshot of the project website',
  },
  {
    number: '03',
    type: 'NONPROFIT / COMMUNITY',
    title: 'PRPL Org',
    description: 'Engineered a high-performance nonprofit platform for community engagement.',
    platforms: ['Nonprofit platform', 'Performance'],
    image: 'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?auto=format&fit=crop&w=900&q=75',
    alt: 'Illustrative community gathering photograph; not a screenshot of the project website',
  },
  {
    number: '04',
    type: 'CREATIVE PORTFOLIO',
    title: 'Yamini Malani',
    description: 'Designed a sleek creative portfolio featuring modern web aesthetics.',
    platforms: ['Creative portfolio', 'UI design'],
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=75',
    alt: 'Illustrative creative portrait photograph; not a screenshot of the project website',
  },
  {
    number: '05',
    type: 'FASHION / RESPONSIVE WEB',
    title: 'ONN International',
    description: 'Led complete UI design and responsive HTML coding for a major fashion brand.',
    platforms: ['HTML', 'Responsive UI'],
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=75',
    alt: 'Illustrative fashion shopping photograph; not a screenshot of the project website',
  },
  {
    number: '06',
    type: 'SHOPIFY / E-COMMERCE',
    title: 'GrytSkill',
    description: 'Customized a Shopify store layout, improving checkout flow and user conversion.',
    platforms: ['Shopify', 'E-commerce'],
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=75',
    alt: 'Illustrative e-commerce product photograph; not a screenshot of the project website',
  },
]